#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
## 服务名
#  application:
#    name: gulimall-pms
## nacos 地址
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#
#
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/pms/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#server:
#  port: 10008

#redis 配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    #   password: ''
    #   连接超时时间
    #  timeout: 3000





